---
# vars file for roles/aws-satellite
name: "AWS Satellite/ Deploy Environment"
description: "AWS Satellite / Deploy Environment"
job_type: "run"
become_enabled: true
playbook: "tower_satenv_playbook.yml"
delete_all:
  name: "AWS Satellite / Delete environment"
  description: "AWS Satellite / Delete environment"
  job_type: "run"
  playbook: "delete_env.yml"
  survey_enabled: true
inventory: 
  name: "AWS Development environment"
  description: "AWS Development environment"
  organization: "Default"
  source:
    name: "AWS Development environment"
    description: "AWS Development environment"
    source: "ec2"
    update_on_launch: true
    overwrite: true
    overwrite_vars: true
credential_aws: 
  name: "AWS"
  description: "AWS credentials"
  organization: "Default"
  credential_type: "aws"
  access_key:
  secret_key:
credential: 
  name: "AWS Credential"
  description: "AWS machine credentials"
  organization: "Default"
  credential_type: "ssh"
  username: "ec2-user"
  private_key:
project:
  name: "Deploy AWS Satellite Env"
  description: "Deploy AWS Satellite Env"
  organization: "Default"
  scm_type: git
  scm_url: "https://github.com/hwalter734/GBM-AWS-SatEnv.git" 
create:
  name: "AWS Satellite/ Deploy Environment"
  description: "AWS Satellite/ Deploy Environment"
  job_type: "run"
  playbook: "tower_satenv_playbook.yml"
  organization: "Default"
  survey_enabled: true
  survey_spec:
    name: AWS Hardened Instance survey 
    description: Provisioning a AWS hardened instance
    spec:
      - type: text
        question_name: Please, enter your personal ssh key configured in AWS 
        variable: key_name  
        required: true
        default:

      - type: multiplechoice
        question_name: Please, enter your desired region 
        variable: region 
        required: true
        default: "us-east-1" 
        choices:
          - "us-east-1"

      - type: text 
        question_name: Please, enter your desired VPC name 
        variable: vpc_name 
        required: true
        default: "example1"

      - type: text
        question_name: Please, enter your desired VPC CIDR 
        variable: vpc_cidr_block
        required: true
        default: "12.0.0.0/16"

      - type: text
        question_name: Please, enter your desired Internet Gateway name 
        variable: igw_name
        required: true
        default: "igw_example1" 

      - type: text
        question_name: Please, enter your desired first public subnet name 
        variable: subnet1_name
        required: true
        default: "subnet1-sat-1a" 

      - type: text
        question_name: Please, enter your desired first public subnet name 
        variable: subnet2_name
        required: true
        default: "subnet2-cap-1b" 

      - type: text
        question_name: Please, enter your desired first public subnet CIDR 
        variable: subnet1_cidr
        required: true
        default: "12.0.1.0/24" 

      - type: text
        question_name: Please, enter your desired second public subnet CIDR 
        variable: subnet2_cidr
        required: true
        default: "12.0.2.0/24" 

      - type: text
        question_name: Please, enter your desired first public subnet availability zone
        variable: subnet1_az
        required: true
        default: "us-east-1a" 

      - type: text
        question_name: Please, enter your desired second public subnet availability zone
        variable: subnet2_az
        required: true
        default: "us-east-1b" 

      - type: text
        question_name: Please, enter your desired security gorup of the satellite instance 
        variable: sat_sg_name 
        required: true
        default: "satsg1" 

      - type: text
        question_name: Please, enter your desired security group name of the capsule instance
        variable: cap_sg_name 
        required: true
        default: "capsg1" 

      - type: text
        question_name: Please, enter the description for the security group associated with the satellite instance 
        variable: sat_sg_description 
        required: true
        default: "Security group with ingress and egress TPC rules for Satellite Instance"

      - type: text
        question_name: Please, enter the description for the security group associated with the capsule instance 
        variable: cap_sg_description 
        required: true
        default: "Security group with ingress and egress TPC/UDP rules for the Capsule Instance"

      - type: multiselect 
        question_name: Please, enter the desired inbound ports for the TCP protocol in the satellite instance 
        variable: sat_in_tcp 
        required: true
        default: "443\n80\n5646\n5647\n8000\n8140\n9090\n7\n53\n5000\n22" 
        choices:
          - "443"
          - "80"
          - "5646"
          - "5647"
          - "8000"
          - "8140"
          - "9090"
          - "7"
          - "53"
          - "5000"
          - "22"

      - type: multiselect 
        question_name: Please, enter the desired inbound ports for the UDP protocol in the satellite instance 
        variable: sat_in_udp 
        required: true
        default: "7\n53\n67\n69"
        choices:
          - "7"
          - "53"
          - "67"
          - "69"

      - type: multiselect 
        question_name: Please, enter the desired outbound ports for the TCP protocol of the satellite instance 
        variable: sat_eg_tcp
        required: true
        default: "443\n9090\n80"
        choices:
          - "443"
          - "9090"
          - "80"

      - type: multiselect 
        question_name: Please, enter the desired outbound ports for the UDP protocol of the satellite instance 
        variable: sat_eg_udp
        required: true
        default: "68"
        choices:
          - "68"

      - type: multiselect 
        question_name: Please, enter the desired inbound ports for the TCP protocol of the capsule instance
        variable: cap_in_tcp
        required: true
        default: "5646\n80\n443\n5647\n8000\n8140\n8443\n9090\n53\n22\n5000"
        choices:
          - "5646"
          - "80"
          - "443"
          - "5647"
          - "8000"
          - "8140"
          - "8443"
          - "9090"
          - "53"
          - "22"
          - "5000"

      - type: multiselect 
        question_name: Please, enter the desired inbound ports for the UDP protocol of the capsule instance
        variable: cap_in_udp
        required: true
        default: "53\n67\n69"
        choices:
          - "53"
          - "67"
          - "69"

      - type: multiselect 
        question_name: Please, enter the desired outbound ports for the TCP protocol of the capsule instance
        variable: cap_eg_tcp
        required: true
        default: "7\n8443"
        choices:
          - "7"
          - "8443"

      - type: multiselect 
        question_name: Please, enter the desired outbound ports for the UDP protocol of the capsule instance
        variable: cap_eg_udp
        required: true
        default: "68"
        choices:
          - "68"
          - "8443"

      - type: text
        question_name: Please, enter the desired AMI image id to use in both instances. 
        question_description: The image needs to be a RHEL 7.x or more recent
        variable: ami_id 
        required: true
        default: "ami-005b7876121b7244d"

      - type: text
        question_name: Please, enter the name of the satellite instance 
        variable: sat_instance_name 
        required: true
        default: "satserver"

      - type: multiplechoice
        question_name: Please, enter the name of the satellite instance 
        variable: sat_instance_size
        required: true
        default: "m4.2xlarge"
        choices: 
          - "m4.2xlarge"

      - type: text
        question_name: Please, enter the name of the capsule instance 
        variable: cap_instance_name 
        required: true
        default: "capserver"

      - type: multiplechoice
        question_name: Please, enter the size of the capsule instance 
        variable: cap_instance_size
        required: true
        default: "m4.xlarge"
        choices: 
          - "m4.xlarge"

            # schema:
            #   - job_template: "{{ create.name }}"
            #     success:
            #       - inventory_source: "{{ inventory.name }}"
            #         failure:
            #           - job_template: "{{ delete_all.name }}"
